### ISSUE TITLE
Problème sous ubuntu 24.04 release candidate 4

### ISSUE THREAD

**Issue by itwars** [cnumr/EcoindexApp#11]
Bonjour,

Je rencontre un non fonctionnement sur Ubuntu 24.04 : 

- quand je clique sur le .deb directement dans le browser de fichiers, il m'indique un problème de dépendances : 
![ecoindex-app1](https://github.com/user-attachments/assets/887a352e-6fe4-4972-822c-03a0187afe04)
- quand je lance l'installation depuis la ligne de commande : ```sudo dpkg -i ecoindex-app_0.2.0.rc.4_amd64.deb``` aucune dépendance n'est installée
- je vois dans la partie basse l'information Chargement pour le Lighthouse-plugin-ecoindex : 
![Screenshot_20241004_142801](https://github.com/user-attachments/assets/0de1fc14-0d5b-4cbc-b465-bc9f6caee69f)
- quand je démarre le scan, j'ai une popup qui indique que ça bosse, mais le répertoire est vide en fin de scan

Merci.

**Comment by hrenaud** [comment]
Une version 0.2.0 vient d'être livré, elle devrait corriger un problème d'installation des dépendances.

Le .deb est l'application desktop. Elle n'a pas à ma connaissance (je ne sais pas comment fonctionne le packaging sous Linux) de dépendances particulières.

Par contre l'outil de mesure, piloté par l'application (qui n'est qu'une GUI) utilise :
- NodeJS (supp ou égale à la version 20) ;
- le plugin `lighthouse-plugin-ecoindex` ;
- un browser chrome headless pour `puppeteer`.

Ces dépendances sont installées lors du premier lancement et mise à jour lors des lancements suivant.

Electron, sous Linux, ne semble pas gérer la mise à jour de l'application, donc il faudra venir la mise à jour de temps en temps, tant que je ne trouve pas un moyen de remplacer le système inclus par un autre, prenant en charge Linux.

Je n'ai pas de Linux pour tester, donc je vais à l'aveugle...

**Comment by hrenaud** [comment]
Je vois que dans la [configuration](https://js.electronforge.io/interfaces/_electron_forge_maker_rpm.InternalOptions.MakerRpmConfigOptions.html#requires) du builder de package pour Linux, on pourrait déclarer des nécessaires au bon démarrage de l'application. À part Node, le reste devrait s'installer automatiquement au lancement de l'application (le résultat se fait dans le footer en effet).

Teste la v0.2.0 et fait mois des retours si possible.

Il y à un fichier log accessible dans Aide > Log... de l'application

**Comment by hrenaud** [comment]
Fix in release 0.3.0, pourrais tu tester @itwars ?

**Comment by itwars** [comment]
Fix :+1:
